--------------------------------------------------------
--  DDL for Trigger XXCPC_CONTRACTS_A_BRI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "WKSP_XXCPC"."XXCPC_CONTRACTS_A_BRI" BEFORE INSERT ON XXCPC_CONTRACTS_A REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
:NEW.EXE_ORDER := XXCPC_EXE_ORDER_SEQ.NEXTVAL;
 END;

/
ALTER TRIGGER "WKSP_XXCPC"."XXCPC_CONTRACTS_A_BRI" ENABLE;
