--------------------------------------------------------
--  DDL for Index XXCT_LOOKUP_VALUES_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "WKSP_XXCT"."XXCT_LOOKUP_VALUES_UK2" ON "WKSP_XXCT"."XXCT_LOOKUP_VALUES" ("LOOKUP_TYPE", "CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
