--------------------------------------------------------
--  DDL for Table XXCT_DSSR_PRDCT_GRPS_HST_BCKP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_DSSR_PRDCT_GRPS_HST_BCKP" 
   (	"DSSR_PRDCT_GRP_HST_ID" NUMBER, 
	"DOSSIER_ID" NUMBER, 
	"DOSSIER_STATUS_OLD" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DOSSIER_STATUS_NEW" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCT_GROUP_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TARGET" NUMBER, 
	"CONTRIBUTION" NUMBER, 
	"AMOUNT" NUMBER, 
	"REMARKS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_DATE" DATE, 
	"MANDATE_CYCLE" NUMBER, 
	"REOPEND_SEQUENCE" NUMBER, 
	"BACK_TO_CONTROLE_SEQUENCE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
