--------------------------------------------------------
--  DDL for Table XXCT_FITAR_FILES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_FITAR_FILES" 
   (	"FILE_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_CONTENT_TYPE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP" DEFAULT (USERENV('LANG')), 
	"ORACLE_CHARSET" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT (SUBSTR(USERENV( 'LANGUAGE'),INSTR(USERENV('LANGUAGE'),'.')+1) ), 
	"FILE_FORMAT" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_DATA" BLOB, 
	"CT_PAYRUN_ID" NUMBER, 
	"UPLOAD_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("FILE_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON TABLE "WKSP_XXCT"."XXCT_FITAR_FILES"  IS '$Id: tbl_XXCT_FITAR_FILES.sql,v 1.1 2019/02/11 13:45:28 rikke493 Exp $';
