--------------------------------------------------------
--  DDL for Table XXCT_DSSR_PRDCT_GRPS_HST_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_DSSR_PRDCT_GRPS_HST_TMP" 
   (	"DOSSIER_ID" NUMBER, 
	"DOSSIER_STATUS_OLD" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DOSSIER_STATUS_NEW" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENT_AMOUNT" NUMBER, 
	"PREVIOUS_AMOUNT" NUMBER, 
	"PRODUCT_GROUP_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MANDATE_CYCLE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
