--------------------------------------------------------
--  DDL for Table XXCT_CAT_PAY_TYPES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_CAT_PAY_TYPES" 
   (	"CAT_PAY_TYPE_ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"PAYMENT_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXCT"."XXCT_CAT_PAY_TYPES"  IS '$Id: tbl_XXCT_CAT_PAY_TYPES.sql,v 1.3 2018/11/27 12:38:55 rikke493 Exp $';
