--------------------------------------------------------
--  DDL for Table XXCT_WF_CT_APPR_HIST_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_WF_CT_APPR_HIST_TMP" 
   (	"ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"WORKFLOWID" NUMBER, 
	"NODENAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INITIATOR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INITIATORNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTOR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTORNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ISFORCEDBY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATEACTIONED" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"WEBREPORTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTACHMENTS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOCUMENTID" NUMBER, 
	"TOKENID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
