--------------------------------------------------------
--  DDL for Table XXCT_CTPAYOUTAPPROVALWF
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_CTPAYOUTAPPROVALWF" 
   (	"DOSSIERID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LINENR" NUMBER(*,0), 
	"DOSSIERTYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIONTYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DOSSIERNUMBER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNERVCODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNERNAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"BONUSPARTNERTYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCTGROUPNAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PRODUCTGROUPCOMMENT" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENTTYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"VATCODE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"LINEAMOUNT" NUMBER, 
	"TOTALAMOUNT" NUMBER, 
	"DOSSIERUNDERPINNEDDOCUMENTSURL" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"Comment" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVED" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVEDANDSYNCHED" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"DELETE" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMIDAPPROVAL" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMIDPAY" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"INVOICENUMBER" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PAID" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"PAIDANDSYNCHED" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYDATE" DATE, 
	"COMMENTFLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"SHAREPARTNERFLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PAYMENTINCLUDE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
