--------------------------------------------------------
--  DDL for Table XXCT_NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_NOTIFICATIONS" 
   (	"NOTIFICATION_ID" NUMBER, 
	"NOT_TYPE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_FROM" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_CC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_BCC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_SUBJECT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_BODY" CLOB COLLATE "USING_NLS_COMP", 
	"NOT_ATTACHMENTS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NOT_DOSSIER_ID" NUMBER, 
	"NOT_STATUS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("NOT_BODY") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON TABLE "WKSP_XXCT"."XXCT_NOTIFICATIONS"  IS '$Id: tbl_XXCT_NOTIFICATIONS.sql,v 1.2 2019/01/03 22:56:28 bakke619 Exp $';
