--------------------------------------------------------
--  DDL for Table XXCT_APPROVALS_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_APPROVALS_TMP" 
   (	"DOSSIERID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BONUSPARTNERTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOSSIERTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIONTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MINAMOUNT" NUMBER, 
	"MAXAMOUNT" NUMBER, 
	"PAYEEID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVALCYCLE" NUMBER, 
	"APPROVALSTATUS" VARCHAR2(32767 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVALDATETIME" DATE, 
	"COMMENTS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVALLEVEL" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
