--------------------------------------------------------
--  DDL for Table XXCT_CTPAYTAPPRVLWFDTLS_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_CTPAYTAPPRVLWFDTLS_TMP" 
   (	"DOSSIERKEY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVERID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DOSSIERID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVALCYCLE" NUMBER, 
	"DOSSIERTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIONTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVERTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SWIMLANE" NUMBER, 
	"ASSIGNEDDATETIME" DATE, 
	"APPROVALSTATUS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"APPROVALDATETIME" DATE, 
	"COMMENTS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMENTDATE" DATE, 
	"APPROVERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
