--------------------------------------------------------
--  DDL for Table XXCT_WORKFLOWLEVELS_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_WORKFLOWLEVELS_TMP" 
   (	"ROLEID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTIONTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BONUSPARTNERTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"MINAMOUNT" NUMBER, 
	"MAXAMOUNT" NUMBER, 
	"APPROVALLEVELS" NUMBER, 
	"APPROVALLEVEL" NUMBER, 
	"DOSSIERTYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INDICATORWORKFLOWROLE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"ROLEAPPROVALLEVELFROM" NUMBER, 
	"ROLEAPPROVALLEVELTO" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
