--------------------------------------------------------
--  DDL for Table XXCT_EXHIBITS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_EXHIBITS" 
   (	"FILE_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_CONTENT_TYPE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP" DEFAULT (USERENV('LANG')), 
	"ORACLE_CHARSET" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT (SUBSTR(USERENV( 'LANGUAGE'),INSTR(USERENV('LANGUAGE'),'.')+1) ), 
	"FILE_FORMAT" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_DATA" BLOB, 
	"UPLOAD_DATE" DATE, 
	"ORG_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DOSSIER_ID" NUMBER, 
	"REMARKS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"COPY_PARTNER" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PUBLISHED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PUBLISHED_DATE" DATE, 
	"TV_FILE_ID" NUMBER, 
	"FILE_SIZE" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("FILE_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "WKSP_XXCT"."XXCT_EXHIBITS"  IS '$Id: tbl_XXCT_EXHIBITS.sql,v 1.1 2018/12/05 15:18:54 rikke493 Exp $';
