--------------------------------------------------------
--  DDL for Table XXCT_PRODUCT_GROUPS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_PRODUCT_GROUPS" 
   (	"CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MEANING" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ENABLED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"BRAND" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"VAT_CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DIGITAL_PRODUCT_GROUP_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"VAT_CODE_EU" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"VAT_CODE_NON_EU" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCOUNTING_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ACQRET_KEY" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
