--------------------------------------------------------
--  DDL for Table XXCT_REMARKS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_REMARKS" 
   (	"REMARK_ID" NUMBER, 
	"DOSSIER_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"JOB_ID" NUMBER, 
	"REMARK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXCT"."XXCT_REMARKS"  IS '$Id: tbl_XXCT_REMARKS.sql,v 1.1 2018/12/05 15:19:21 rikke493 Exp $';
