--------------------------------------------------------
--  DDL for Table XXCT_PARTNERS_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_PARTNERS_TMP" 
   (	"PARTNER_ID" NUMBER, 
	"PARTNER_NAME" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"V_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANNEL_MANAGER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"RESOURCE_ID" NUMBER, 
	"CHANNEL_MANAGER_PERSON_ID" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNER_NUMBER" NUMBER, 
	"EMAIL_ADDRESS_INVOICE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNER_FLOW_TYPE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ORACLE_CUSTOMER_NR" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"VAT_REVERSE_CHARGE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
