--------------------------------------------------------
--  DDL for Table XXCT_LOOKUPS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_LOOKUPS" 
   (	"LOOKUP_ID" NUMBER DEFAULT ON NULL "WKSP_XXCT"."XXCT_LOOKUPS_SEQ"."NEXTVAL", 
	"LOOKUP_TYPE" VARCHAR2(28 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
