--------------------------------------------------------
--  DDL for Table XXCT_PERSONS_TMP
--------------------------------------------------------

  CREATE TABLE "WKSP_XXCT"."XXCT_PERSONS_TMP" 
   (	"USER_ID" NUMBER, 
	"PERSON_ID" NUMBER, 
	"FULL_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"JOB_ID" NUMBER, 
	"JOB_NAME" CHAR(8 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_ID" NUMBER, 
	"POSITION_NAME" CHAR(13 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NAME" VARCHAR2(200 CHAR) COLLATE "USING_NLS_COMP", 
	"DISPLAY_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RUIS_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
