--------------------------------------------------------
--  DDL for Sequence XXCPC_CORRECTIONAMOUNTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WKSP_XXCPC"."XXCPC_CORRECTIONAMOUNTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5220 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
