--------------------------------------------------------
--  DDL for Table XXAPI_BATCH_COUNTERS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" 
   (	"BCS_BAH_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BCS_DESCRIPTION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BCS_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BCS_BRT_CODE_READ" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BCS_BRT_CODE_PROCESSED" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BCS_IND_TONEN_BIJ_FUNC_BRN" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"BCS_IND_BRT_IN_OMS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"BCS_PRINTING_ORDER" NUMBER DEFAULT 10
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS"  IS '$Id: tbl_XXAPI_BATCH_COUNTERS.sql,v 1.1 2024/09/20 16:04:58 bakke619 Exp $';
  GRANT ALTER ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DELETE ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INDEX ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INSERT ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT SELECT ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT UPDATE ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT REFERENCES ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DEBUG ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" TO "WKSP_XXPM" WITH GRANT OPTION;
