--------------------------------------------------------
--  DDL for Table XXAPI_LOOKUPS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_LOOKUPS" 
   (	"LOOKUP_ID" NUMBER DEFAULT ON NULL WKSP_XXAPI.XXAPI_LOOKUPS_S.NEXTVAL, 
	"LOOKUP_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_LOOKUPS"  IS '$Id: tbl_XXAPI_LOOKUPS.sql,v 1.1 2024/09/20 16:05:50 bakke619 Exp $';
