--------------------------------------------------------
--  DDL for Table XXAPI_DEBUG
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_DEBUG" 
   (	"SEQ_NR" NUMBER, 
	"ROUTINE" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP" DEFAULT NULL, 
	"MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MESSAGE_CLOB" CLOB COLLATE "USING_NLS_COMP", 
	"MESSAGE_BLOB" BLOB, 
	"PROC_LEVEL" NUMBER, 
	"TIMESTAMP" DATE, 
	"DURATION" NUMBER, 
	"SESSION_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("MESSAGE_CLOB") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MESSAGE_BLOB") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
