--------------------------------------------------------
--  DDL for Table XXAPI_EMAILS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_EMAILS" 
   (	"EMAIL_ID" NUMBER, 
	"EMAIL_FROM" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_TO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_CC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_BCC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_SUBJECT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_BODY" CLOB COLLATE "USING_NLS_COMP", 
	"EMAIL_MESSAGE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_ATTACHMENTS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_COMMENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_STATUS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_AT_TESTCASE_ID" NUMBER DEFAULT -1, 
	"EMAIL_AT_STATUS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_AT_TESTED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("EMAIL_BODY") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_EMAILS"  IS '$Id: tbl_XXAPI_EMAILS.sql,v 1.1 2024/09/20 16:05:45 bakke619 Exp $';
  GRANT DELETE ON "WKSP_XXAPI"."XXAPI_EMAILS" TO "WKSP_XXPM";
  GRANT INSERT ON "WKSP_XXAPI"."XXAPI_EMAILS" TO "WKSP_XXPM";
  GRANT SELECT ON "WKSP_XXAPI"."XXAPI_EMAILS" TO "WKSP_XXPM";
  GRANT UPDATE ON "WKSP_XXAPI"."XXAPI_EMAILS" TO "WKSP_XXPM";
