--------------------------------------------------------
--  DDL for Table XXAPI_BATCH_RUNS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_BATCH_RUNS" 
   (	"BRN_ID" NUMBER(10,0), 
	"BRN_BAH_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BRN_STARTDATE" DATE, 
	"BRN_ENDDATE" DATE, 
	"BRN_USER_NAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"BRN_INDICATOR_OK" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"BRN_ERROR" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"BRN_ID_UNDO" NUMBER(10,0), 
	"BRN_DATE_UNDO" DATE, 
	"BRN_USER_NAME_UNDO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"BRN_ID_MAIN" NUMBER(10,0), 
	"BRN_ID_FUNCTIONAL" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_BATCH_RUNS"  IS '$Id: tbl_XXAPI_BATCH_RUNS.sql,v 1.1 2024/09/20 16:05:14 bakke619 Exp $';
  GRANT ALTER ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DELETE ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INDEX ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INSERT ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT SELECT ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT UPDATE ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT REFERENCES ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DEBUG ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" TO "WKSP_XXPM" WITH GRANT OPTION;
