--------------------------------------------------------
--  DDL for Table XXAPI_BATCH_RUN_FAILURES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" 
   (	"BRL_ID" NUMBER(10,0), 
	"BRL_BRN_ID" NUMBER(10,0), 
	"BRL_LINE_NR" NUMBER(10,0), 
	"BRL_LINE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"BRL_FILE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BRL_BAH_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BRL_BFT_CODE" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"BRL_PARAMETER" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BRL_OR_BRN_ID" NUMBER(10,0), 
	"BRL_CREATION_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES"  IS '$Id: tbl_XXAPI_BATCH_RUN_FAILURES.sql,v 1.1 2024/09/20 16:05:24 bakke619 Exp $';
  GRANT ALTER ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DELETE ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INDEX ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INSERT ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT SELECT ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT UPDATE ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT REFERENCES ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DEBUG ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_FAILURES" TO "WKSP_XXPM" WITH GRANT OPTION;
