--------------------------------------------------------
--  DDL for Table XXAPI_BATCHES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_BATCHES" 
   (	"BAH_CODE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_DESCRIPTION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_PROCES" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_EMAIL_ADDRESS" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_EMAIL_ADDRESS_OUTPUT" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_EMAIL_ADDRESS_CC" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_NEXT_FILE1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_NEXT_FILE2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_NEXT_FILE3" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_NEXT_FILE4" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_MIN_FILES1" NUMBER(3,0), 
	"BAH_MAX_FILES1" NUMBER(4,0), 
	"BAH_MIN_FILES2" NUMBER(3,0), 
	"BAH_MAX_FILES2" NUMBER(4,0), 
	"BAH_INDICATOR_MAIN" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_LOG_INLINE_MAIL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_CODE_BASE_FOR" VARCHAR2(8 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_FTP_TARGET_MACHINE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_FTP_TARGET_DIR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_FTP_LOCAL_DIR" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_ENCRYPT_INDICATOR" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_ENCRYPT_EXTENTION" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BAH_ENCRYPT_SENDER_GROUP_ID" NUMBER, 
	"BAH_ENCRYPT_RECEIVER_GROUP_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_BATCHES"  IS '$Id: tbl_XXAPI_BATCHES.sql,v 1.1 2024/09/20 16:04:52 bakke619 Exp $';
  GRANT ALTER ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DELETE ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INDEX ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INSERT ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT SELECT ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT UPDATE ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT REFERENCES ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DEBUG ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "WKSP_XXAPI"."XXAPI_BATCHES" TO "WKSP_XXPM" WITH GRANT OPTION;
