--------------------------------------------------------
--  DDL for Table XXAPI_BATCH_RUN_SETTINGS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" 
   (	"BRS_BRN_ID" NUMBER(10,0), 
	"BRS_CODE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"BRS_VALUE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS"  IS '$Id: tbl_XXAPI_BATCH_RUN_SETTINGS.sql,v 1.1 2024/09/20 16:05:39 bakke619 Exp $';
  GRANT ALTER ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DELETE ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INDEX ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT INSERT ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT SELECT ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT UPDATE ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT REFERENCES ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT DEBUG ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
  GRANT FLASHBACK ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_SETTINGS" TO "WKSP_XXPM" WITH GRANT OPTION;
