--------------------------------------------------------
--  DDL for Index XXCPC_CORRECTIONAM_I1
--------------------------------------------------------

  CREATE INDEX "WKSP_XXCPC"."XXCPC_CORRECTIONAM_I1" ON "WKSP_XXCPC"."XXCPC_CORRECTIONAMOUNTS" ("PARTNERID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
