--------------------------------------------------------
--  DDL for Index XXCPC_DATA_ACRHIVE_TBLNAME
--------------------------------------------------------

  CREATE INDEX "WKSP_XXCPC"."XXCPC_DATA_ACRHIVE_TBLNAME" ON "WKSP_XXCPC"."XXCPC_DATA_ARCHIVE" ("TABLENAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
