--------------------------------------------------------
--  DDL for Table XXPM_LOOKUP_VALUES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_LOOKUP_VALUES" 
   (	"LOOKUP_TYPE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"MEANING" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"ENABLED_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"ATTRIBUTE1" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
