--------------------------------------------------------
--  DDL for Table XXPM_ADDRESSES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_ADDRESSES" 
   (	"ADDRESS_ID" NUMBER DEFAULT ON NULL "WKSP_XXPM"."XXPM_ADDRESSES_SEQ"."NEXTVAL", 
	"ADDRESS_STREET" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_HOUSE_NUMBER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_HOUSE_NUMBER_SUFFIX" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_ZIP_CODE" VARCHAR2(60 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_RESIDENCE" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_TYPE" NUMBER, 
	"ADDRESS_TYPE_OTHER" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTBUS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_COUNTRY" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"ADDRESS_FUNCTION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNER_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
