--------------------------------------------------------
--  DDL for Table XXPM_DOCUMENTATION
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_DOCUMENTATION" 
   (	"FILE_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNER_FILE_PREFIX" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_CONTENT_TYPE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ORACLE_CHARSET" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_DATA" BLOB, 
	"UPLOAD_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"MSFT_DIRECTORY" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"GPG_ENCRYPT_INDICATOR" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"GPG_ENCRYPTED_FILE_NAME" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"GPG_ENCRYPTION_DATE" DATE, 
	"GPG_ENCRYPTION_RETRY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" 
 LOB ("FILE_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
