--------------------------------------------------------
--  DDL for Table XXPM_AUDIT_DATA
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_AUDIT_DATA" 
   (	"AUDIT_ID" NUMBER, 
	"RECORD_ID" NUMBER DEFAULT -9999, 
	"RECORD_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TRANSACTION_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'U', 
	"FIELD_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA_TYPE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"OLD_VALUE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"NEW_VALUE" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BRN_ID" NUMBER DEFAULT -9999, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON TABLE "WKSP_XXPM"."XXPM_AUDIT_DATA"  IS '$Id: tbl_XXPM_AUDIT_DATA.sql,v 1.2 2020/12/31 17:24:27 bakke619 Exp $';
