--------------------------------------------------------
--  DDL for Table XXPM_ALL_PEOPLE_MIG
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_ALL_PEOPLE_MIG" 
   (	"PERSON_ID" NUMBER, 
	"FULL_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONAL_IDENTIFIER" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
