--------------------------------------------------------
--  DDL for Index XXPM_AUDIT_DATA_IDX02
--------------------------------------------------------

  CREATE INDEX "WKSP_XXPM"."XXPM_AUDIT_DATA_IDX02" ON "WKSP_XXPM"."XXPM_AUDIT_DATA" ("CREATED_BRN_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
