--------------------------------------------------------
--  DDL for Index XXPM_ALL_JOBS_JOB_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WKSP_XXPM"."XXPM_ALL_JOBS_JOB_ID_PK" ON "WKSP_XXPM"."XXPM_ALL_JOBS" ("JOB_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
