--------------------------------------------------------
--  DDL for Index XXPM_PARTNERS_I1
--------------------------------------------------------

  CREATE INDEX "WKSP_XXPM"."XXPM_PARTNERS_I1" ON "WKSP_XXPM"."XXPM_PARTNERS" ("MAIN_PARTNER_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
