--------------------------------------------------------
--  DDL for Table XXPM_CHAINS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_CHAINS" 
   (	"CHAIN_ID" NUMBER DEFAULT ON NULL "WKSP_XXPM"."XXPM_CHAINS_SEQ"."NEXTVAL", 
	"CHAIN_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"INDICATOR_IN_EX" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"CENTER_CODE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"SALES_CHANNEL_DISTRIBUTION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SALES_CHANNEL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SUB_SALES_CHANNEL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CHANNEL_MIX" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
