--------------------------------------------------------
--  DDL for Table XXPM_USERS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_USERS" 
   (	"USER_ID" NUMBER DEFAULT ON NULL "WKSP_XXPM"."XXPM_USERS_SEQ"."NEXTVAL", 
	"USER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL_ADDRESS" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ALLOW_UPLOAD_DOCUMENTS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"RUIS_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
