--------------------------------------------------------
--  DDL for Table XXPM_CONTACTS
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_CONTACTS" 
   (	"CONTACT_ID" NUMBER DEFAULT ON NULL "WKSP_XXPM"."XXPM_CONTACTS_SEQ"."NEXTVAL", 
	"CONTACT_ID_SALESFORCE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '-99999999', 
	"CONTACT_FIRST_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_INITIALS" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PREFIX" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_LAST_NAME" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_TITLE" NUMBER, 
	"CONTACT_PHONE_NUMBER" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_PHONE_NUMBER_MOBILE" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_DATE_OF_BIRTH" DATE, 
	"CONTACT_EMAIL_ADDRESS" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_TYPE" NUMBER, 
	"CONTACT_TYPE_OTHER" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_FUNCTION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_REMARKS" VARCHAR2(400 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_ACTIVE_INDICATOR" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PARTNER_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
