--------------------------------------------------------
--  DDL for Table XXPM_FILES
--------------------------------------------------------

  CREATE TABLE "WKSP_XXPM"."XXPM_FILES" 
   (	"FILE_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_CONTENT_TYPE" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"LANGUAGE" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP" DEFAULT (USERENV('LANG')), 
	"ORACLE_CHARSET" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT (SUBSTR(USERENV( 'LANGUAGE'),INSTR(USERENV('LANGUAGE'),'.')+1) ), 
	"FILE_FORMAT" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_DATA" BLOB, 
	"FILE_CONTENT_LENGTH" NUMBER, 
	"HASH_VALUE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VALIDATION_CODE" NUMBER, 
	"PROCESSING_CODE" NUMBER, 
	"UPLOAD_DATE" DATE, 
	"VALIDATION_DATE" DATE, 
	"PROCESSED_DATE" DATE, 
	"STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"RETRY_COUNT" NUMBER, 
	"ORG_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("FILE_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON TABLE "WKSP_XXPM"."XXPM_FILES"  IS '$Id: tbl_XXpm_FILES.sql,v 1.8 2021/03/19 12:35:18 bakke619 Exp $';
