--------------------------------------------------------
--  DDL for View XXCT_SPCTWFLEVELS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXCT"."XXCT_SPCTWFLEVELS_V" ("SWIMLANE", "BONUSPARTNERTYPE", "DOSSIERTYPE", "ACTIONTYPE", "LEVEL", "MINAMOUNT", "MAXAMOUNT", "ROLEAPPROVALLEVELFROM", "ROLEAPPROVALLEVELTO", "DESCRIPTION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select "SWIMLANE","BONUSPARTNERTYPE","DOSSIERTYPE","ACTIONTYPE","APPROVALLEVEL","MINAMOUNT","MAXAMOUNT","ROLEAPPROVALLEVELFROM","ROLEAPPROVALLEVELTO","DESCRIPTION" from table( XXCT_GEN_REST_APIS.get_spCTWFLevels)
;
