--------------------------------------------------------
--  DDL for View XXCT_HEROPEND_DOSSIER_PAGE15_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXCT"."XXCT_HEROPEND_DOSSIER_PAGE15_V" ("CHECKBOX", "DOSSIER_ID", "LETTER_NUMBER", "CRS", "CATEGORY", "PARTNER_V_CODE", "PARTNER_NAME", "PRODUCT_CODE", "PRODUCT_NAME", "PRE_REMARKS", "PRE_TARGET", "PRE_CONTRIBUTION", "PRE_AMOUNT", "PAYMENT_TARGET", "PAYMENT_CONTRIBUTION", "PAYMENT_AMOUNT", "DIFF_AMOUNT", "NEW_TARGET", "NEW_CONTRIBUTION", "NEW_AMOUNT", "NEW_REMARKS", "REST_BEDRAG", "DOSSIER_CATEGORY_ID", "RESOURCE_ID", "LETTER_NUMBER_YEAR") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT '' CHECKBOX, DOSSIER_ID, LETTER_NUMBER, CRS, CATEGORY, PARTNER_V_CODE, PARTNER_NAME, PRODUCT_CODE, PRODUCT_NAME, PRE_REMARKS, 
       PRE_TARGET, PRE_CONTRIBUTION, PRE_AMOUNT, PAYMENT_TARGET, PAYMENT_CONTRIBUTION, PAYMENT_AMOUNT,DIFF_AMOUNT, 
       NEW_TARGET, --(PRE_TARGET - PAYMENT_TARGET) NEW_TARGET,
       NEW_CONTRIBUTION, --(PRE_CONTRIBUTION - PAYMENT_CONTRIBUTION) NEW_CONTRIBUTION,
       NEW_AMOUNT,
       NEW_REMARKS,
       (NVL(NEW_AMOUNT,0) - NVL(PAYMENT_AMOUNT,0)) REST_BEDRAG,
       DOSSIER_CATEGORY_ID,
       RESOURCE_ID,
       LETTER_NUMBER_YEAR
  FROM (
SELECT A.DOSSIER_ID,A.LETTER_NUMBER,
(SELECT flv.meaning
   FROM xxct_lookup_values flv,
        xxct_cat_prod_groups cpg,
        xxct_categories xc,
        xxct_dossiers xd
  WHERE flv.lookup_type        = 'MAIN_CATEGORIES'
    AND SYSDATE                BETWEEN flv.start_date_active AND NVL(flv.end_date_active, TO_DATE ('31-12-4712', 'DD-MM-YYYY'))
    AND xc.category_id         = cpg.category_id
    AND flv.code               = xc.main_category
    AND cpg.product_group_code = C.product_group_code
    AND cpg.product_group_code = C.product_group_code
    AND xd.dossier_id          = C.dossier_id
    AND xd.dossier_category_id = xc.category_id
) CRS,
A.CATEGORY, A.V_CODE_BUSINESS_PARTNER PARTNER_V_CODE,A.BUSINESS_PARTNER PARTNER_NAME,C.PRODUCT_GROUP_CODE PRODUCT_CODE,
(SELECT MEANING FROM XXCT_PRODUCT_GROUPS WHERE CODE = C.PRODUCT_GROUP_CODE ) PRODUCT_NAME,
D.PRE_REMARKS PRE_REMARKS,NVL(D.PRE_TARGET,0) PRE_TARGET,NVL(D.PRE_CONTRIBUTION,0) PRE_CONTRIBUTION,NVL(D.PRE_AMOUNT,0) PRE_AMOUNT,
--C.REMARKS PRE_REMARKS,NVL(C.TARGET,0) PRE_TARGET,NVL(C.CONTRIBUTION,0) PRE_CONTRIBUTION,NVL(C.CURR_AMOUNT,0) PRE_AMOUNT,
NVL(E.PAY_TARGET,0) PAYMENT_TARGET,NVL(E.PAY_CONTRIBUTION,0) PAYMENT_CONTRIBUTION,NVL(E.PAY_AMOUNT,0) PAYMENT_AMOUNT,
(NVL(D.PRE_AMOUNT,0) - NVL(E.PAY_AMOUNT,0)) DIFF_AMOUNT,
--CASE WHEN NVL(D.TARGET,0) <> NVL(C.TARGET,0) THEN NVL(C.TARGET,0) ELSE (NVL(D.TARGET,0) - NVL(E.TARGET,0)) END NEW_TARGET,
--CASE WHEN NVL(D.CONTRIBUTION,0) <> NVL(C.CONTRIBUTION,0) THEN NVL(C.CONTRIBUTION,0) ELSE (NVL(D.CONTRIBUTION,0) - NVL(E.CONTRIBUTION,0)) END NEW_CONTRIBUTION,
--CASE WHEN NVL(D.AMOUNT,0) <> NVL(C.CURR_AMOUNT,0) THEN NVL(C.CURR_AMOUNT,0) ELSE (NVL(D.AMOUNT,0) - NVL(E.AMOUNT,0)) END NEW_AMOUNT,
CASE WHEN NVL(DD.PRE_TARGET_NEW,0)       <> NVL(C.CURR_TARGET,0)       THEN NVL(C.CURR_TARGET,0)       ELSE NVL(E.PAY_TARGET,0) END NEW_TARGET,
CASE WHEN NVL(DD.PRE_CONTRIBUTION_NEW,0) <> NVL(C.CURR_CONTRIBUTION,0) THEN NVL(C.CURR_CONTRIBUTION,0) ELSE NVL(E.PAY_CONTRIBUTION,0) END NEW_CONTRIBUTION,
CASE WHEN NVL(DD.PRE_AMOUNT_NEW,0)       <> NVL(C.CURR_AMOUNT,0)       THEN NVL(C.CURR_AMOUNT,0)       ELSE NVL(E.PAY_AMOUNT,0) END NEW_AMOUNT,
CASE WHEN SUBSTR(C.CURR_REMARKS,-9) = '(Vrijval)' THEN C.CURR_REMARKS ELSE C.CURR_REMARKS ||' (Vrijval)' END NEW_REMARKS,
A.DOSSIER_CATEGORY_ID,
A.RESOURCE_ID,
A.LETTER_NUMBER_YEAR
FROM XXCT_DOSSIERS_V A,--XXCT_DOSSIER_PRODUCT_GROUPS C,
(SELECT AA.DOSSIER_ID,AA.PRODUCT_GROUP_CODE,AA.TARGET CURR_TARGET,AA.CONTRIBUTION CURR_CONTRIBUTION,AA.AMOUNT CURR_AMOUNT,AA.REMARKS CURR_REMARKS
   FROM XXCT_DOSSIER_PRODUCT_GROUPS AA,XXCT_DOSSIERS BB WHERE AA.DOSSIER_ID = BB.DOSSIER_ID AND BB.DOSSIER_TYPE = 'RESERVATION' AND STATUS IN ('HEROPEND','OPEN')) C,
(select pgh2.dossier_id,pgh2.dssr_prdct_grp_hst_id,pgh2.product_group_code,pgh2.TARGET PRE_TARGET_NEW,pgh2.CONTRIBUTION PRE_CONTRIBUTION_NEW,pgh2.AMOUNT PRE_AMOUNT_NEW,pgh2.remarks,pgh2.status_date
   from XXCT_DSSR_PRDCT_GRPS_HST pgh2,
        XXCT_REP_2_MAX_ID_BCED_V mid2
  where 1=1
    and mid2.dossier_id             = pgh2.dossier_id
    and mid2.product_group_code     = pgh2.product_group_code
    and mid2.dssr_prdct_grp_hst_id  = pgh2.dssr_prdct_grp_hst_id   
    and pgh2.dossier_id in (select distinct coalesce(dos2.parent_dossier_id,dos2.dossier_id) dossier_id 
                              from XXCT_DSSR_PRDCT_GRPS_HST pgh1,
                                   XXCT_REP_2_MAX_ID_BCED_V mid,
                                   XXCT_DOSSIERS_V dos2 
                             where 1=1
                               AND dos2.DOSSIER_TYPE         = 'RESERVATION'
                               AND dos2.STATUS               IN ('HEROPEND','OPEN')
                               and dos2.dossier_id           = pgh1.dossier_id 
                               and mid.dossier_id            = pgh1.dossier_id
                               and mid.product_group_code    = pgh1.product_group_code
                               and mid.dssr_prdct_grp_hst_id = pgh1.dssr_prdct_grp_hst_id
                    )
) DD,
(SELECT DOSSIER_ID,PRODUCT_GROUP_CODE,TARGET PRE_TARGET,CONTRIBUTION PRE_CONTRIBUTION,AMOUNT PRE_AMOUNT,REMARKS PRE_REMARKS
FROM xxct_dssr_prdct_grps_hst WHERE DOSSIER_STATUS_NEW = 'AFGESLOTEN' AND (DOSSIER_ID,MANDATE_CYCLE) IN (
        SELECT DOSSIER_ID,MAX(MANDATE_CYCLE) FROM (
        SELECT A.DOSSIER_ID,A.MANDATE_CYCLE FROM xxct_dssr_prdct_grps_hst A,XXCT_DOSSIERS B
        WHERE A.DOSSIER_ID = B.DOSSIER_ID AND A.MANDATE_CYCLE < B.MANDATE_CYCLE AND DOSSIER_STATUS_NEW = 'AFGESLOTEN' ORDER BY 1
        ) GROUP BY DOSSIER_ID
        )) D,
(SELECT A.PARENT_DOSSIER_ID DOSSIER_ID,B.PRODUCT_GROUP_CODE,SUM(NVL(B.TARGET,0)) PAY_TARGET,SUM(NVL(CONTRIBUTION,0)) PAY_CONTRIBUTION,SUM(NVL(AMOUNT,0)) PAY_AMOUNT
FROM XXCT_DOSSIERS A,xxct_dossier_product_groups B WHERE A.DOSSIER_ID = B.DOSSIER_ID
AND A.DOSSIER_TYPE = 'PAYMENT' AND PARENT_DOSSIER_ID IN (
SELECT DOSSIER_ID FROM XXCT_DOSSIERS WHERE DOSSIER_TYPE = 'RESERVATION' AND STATUS IN ('HEROPEND','OPEN') )
GROUP BY A.PARENT_DOSSIER_ID,B.PRODUCT_GROUP_CODE
) E
WHERE 1=1
  AND A.DOSSIER_TYPE        = 'RESERVATION'
  AND A.STATUS              IN ('HEROPEND','OPEN')
  AND A.DOSSIER_ID          = C.DOSSIER_ID
  AND C.DOSSIER_ID          = D.DOSSIER_ID
  AND C.PRODUCT_GROUP_CODE  = D.PRODUCT_GROUP_CODE
  AND D.DOSSIER_ID          = E.DOSSIER_ID(+)
  AND C.DOSSIER_ID          = E.DOSSIER_ID(+)
  AND C.PRODUCT_GROUP_CODE  = E.PRODUCT_GROUP_CODE(+)
  AND C.DOSSIER_ID          = DD.DOSSIER_ID
  AND C.PRODUCT_GROUP_CODE  = DD.PRODUCT_GROUP_CODE
  --AND A.DOSSIER_CATEGORY_ID like coalesce(v('P15_CATEGORIE'),'%')
  --AND A.RESOURCE_ID         like coalesce(v('P15_PARTNER'),'%')
  --AND A.LETTER_NUMBER_YEAR  like coalesce(v('P15_YEAR'),'%')
) WHERE 1=1 
    --AND UPPER(CRS) like coalesce(v('P15_CRS'),'%')
ORDER BY DOSSIER_ID DESC,PRODUCT_CODE
;
