--------------------------------------------------------
--  DDL for View XXCT_DECREASE_DOSSIERS_PAGE19_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXCT"."XXCT_DECREASE_DOSSIERS_PAGE19_V" ("CHECKBOX", "DOSSIER_ID", "LETTER_NUMBER", "CRS", "CATEGORY", "PARTNER_V_CODE", "PARTNER_NAME", "PRODUCT_CODE", "PRODUCT_NAME", "PRE_REMARKS", "PRE_TARGET", "PRE_CONTRIBUTION", "PRE_AMOUNT", "PAYMENT_TARGET", "PAYMENT_CONTRIBUTION", "PAYMENT_AMOUNT", "DIFF_AMOUNT", "NEW_TARGET", "NEW_CONTRIBUTION", "NEW_AMOUNT", "NEW_REMARKS", "DOSSIER_CATEGORY_ID", "CRS_FILTER", "RESOURCE_ID", "LETTER_NUMBER_YEAR") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT NULL CHECKBOX, DOSSIER_ID, LETTER_NUMBER, CRS, CATEGORY, PARTNER_V_CODE, PARTNER_NAME, PRODUCT_CODE, PRODUCT_NAME, PRE_REMARKS, 
       PRE_TARGET, PRE_CONTRIBUTION, PRE_AMOUNT, PAYMENT_TARGET, PAYMENT_CONTRIBUTION, PAYMENT_AMOUNT,DIFF_AMOUNT, 
       NEW_TARGET, --(PRE_TARGET - PAYMENT_TARGET) NEW_TARGET,
       NEW_CONTRIBUTION, --(PRE_CONTRIBUTION - PAYMENT_CONTRIBUTION) NEW_CONTRIBUTION,
       NEW_AMOUNT,
       NEW_REMARKS,
       DOSSIER_CATEGORY_ID,
       UPPER(CRS) CRS_FILTER,
       RESOURCE_ID,
       LETTER_NUMBER_YEAR
       FROM (
SELECT A.DOSSIER_ID,A.LETTER_NUMBER,
(SELECT flv.meaning
   FROM xxct_lookup_values flv,
        xxct_cat_prod_groups cpg,
        xxct_categories xc,
        xxct_dossiers xd
  WHERE flv.lookup_type        = 'MAIN_CATEGORIES'
    AND SYSDATE                BETWEEN flv.start_date_active AND NVL(flv.end_date_active, TO_DATE ('31-12-4712', 'DD-MM-YYYY'))
    AND xc.category_id         = cpg.category_id
    AND flv.code               = xc.main_category
    AND cpg.product_group_code = C.product_group_code
    AND cpg.product_group_code = C.product_group_code
    AND xd.dossier_id          = C.dossier_id
    AND xd.dossier_category_id = xc.category_id
) CRS,
A.CATEGORY, A.V_CODE_BUSINESS_PARTNER PARTNER_V_CODE,A.BUSINESS_PARTNER PARTNER_NAME,C.PRODUCT_GROUP_CODE PRODUCT_CODE,
(SELECT MEANING FROM XXCT_PRODUCT_GROUPS WHERE CODE = C.PRODUCT_GROUP_CODE ) PRODUCT_NAME,
D.REMARKS PRE_REMARKS,NVL(D.TARGET,0) PRE_TARGET,NVL(D.CONTRIBUTION,0) PRE_CONTRIBUTION,NVL(D.AMOUNT,0) PRE_AMOUNT,
--C.REMARKS PRE_REMARKS,NVL(C.TARGET,0) PRE_TARGET,NVL(C.CONTRIBUTION,0) PRE_CONTRIBUTION,NVL(C.AMOUNT,0) PRE_AMOUNT,
NVL(E.TARGET,0) PAYMENT_TARGET,NVL(E.CONTRIBUTION,0) PAYMENT_CONTRIBUTION,NVL(E.AMOUNT,0) PAYMENT_AMOUNT,
(NVL(D.AMOUNT,0) - NVL(E.AMOUNT,0)) DIFF_AMOUNT,
NVL(C.TARGET,0) NEW_TARGET,
NVL(C.CONTRIBUTION,0) NEW_CONTRIBUTION,
NVL(C.AMOUNT,0) NEW_AMOUNT,
C.REMARKS /*||' (Vrijval)'*/ NEW_REMARKS,
A.DOSSIER_CATEGORY_ID,
A.RESOURCE_ID,
A.LETTER_NUMBER_YEAR

FROM XXCT_DOSSIERS_V A,XXCT_DOSSIER_PRODUCT_GROUPS C,
(SELECT DOSSIER_ID,DSSR_PRDCT_GRP_HST_ID,PRODUCT_GROUP_CODE,TARGET, CONTRIBUTION, AMOUNT,REMARKS
 FROM xxct_dssr_prdct_grps_hst WHERE DOSSIER_STATUS_NEW = 'AFGESLOTEN' AND (DOSSIER_ID,MANDATE_CYCLE) IN (
SELECT DOSSIER_ID,MAX(MANDATE_CYCLE) FROM (
SELECT A.DOSSIER_ID,A.MANDATE_CYCLE FROM xxct_dssr_prdct_grps_hst A,XXCT_DOSSIERS B
WHERE B.DOSSIER_TYPE = 'RESERVATION' AND B.STATUS = 'CONTROLE' AND
A.DOSSIER_ID = B.DOSSIER_ID AND A.MANDATE_CYCLE < B.MANDATE_CYCLE AND DOSSIER_STATUS_NEW = 'AFGESLOTEN' ORDER BY 1
) GROUP BY DOSSIER_ID
)
) D,
(SELECT A.PARENT_DOSSIER_ID DOSSIER_ID,B.PRODUCT_GROUP_CODE,SUM(NVL(B.TARGET,0)) TARGET,SUM(NVL(CONTRIBUTION,0)) CONTRIBUTION,SUM(NVL(AMOUNT,0)) AMOUNT
FROM XXCT_DOSSIERS A,xxct_dossier_product_groups B WHERE A.DOSSIER_ID = B.DOSSIER_ID
AND A.DOSSIER_TYPE = 'PAYMENT' AND PARENT_DOSSIER_ID IN (
SELECT DOSSIER_ID FROM XXCT_DOSSIERS WHERE DOSSIER_TYPE = 'RESERVATION' AND STATUS = 'CONTROLE')
GROUP BY A.PARENT_DOSSIER_ID,B.PRODUCT_GROUP_CODE
) E,
(
SELECT DOSSIER_ID FROM (
SELECT G.DOSSIER_ID,PREV_AMOUNT sum_previous_amount,CURR_AMOUNT sum_current_amount,(NVL(CURR_AMOUNT,0) - NVL(PREV_AMOUNT,0)) CHANGES_AMOUNT
FROM 
(
SELECT DOSSIER_ID,SUM(AMOUNT) PREV_AMOUNT FROM xxct_dssr_prdct_grps_hst WHERE DOSSIER_STATUS_NEW = 'AFGESLOTEN' AND (DOSSIER_ID,MANDATE_CYCLE) IN (
SELECT DOSSIER_ID,MAX(MANDATE_CYCLE) FROM (
SELECT A.DOSSIER_ID,A.MANDATE_CYCLE FROM xxct_dssr_prdct_grps_hst A,XXCT_DOSSIERS B
WHERE B.DOSSIER_TYPE = 'RESERVATION' AND B.STATUS = 'CONTROLE' AND
A.DOSSIER_ID = B.DOSSIER_ID AND A.MANDATE_CYCLE < B.MANDATE_CYCLE AND DOSSIER_STATUS_NEW = 'AFGESLOTEN' ORDER BY 1
) GROUP BY DOSSIER_ID
)GROUP BY DOSSIER_ID) F, --L_PREV_AMOUNT
(
SELECT C.DOSSIER_ID,SUM(D.AMOUNT) CURR_AMOUNT FROM XXCT_DOSSIERS C, xxct_dossier_product_groups D
WHERE C.DOSSIER_ID = D.DOSSIER_ID 
AND C.DOSSIER_TYPE = 'RESERVATION' AND C.STATUS = 'CONTROLE'
GROUP BY C.DOSSIER_ID
) G --L_CURR_AMOUNT
WHERE F.DOSSIER_ID(+) = G.DOSSIER_ID
AND (NVL(CURR_AMOUNT,0) - NVL(PREV_AMOUNT,0)) < 0
)
) FF
WHERE 1=1
  AND A.DOSSIER_TYPE        = 'RESERVATION'
  AND A.STATUS              = 'CONTROLE'
  AND A.DOSSIER_ID          = C.DOSSIER_ID
  AND C.DOSSIER_ID          = D.DOSSIER_ID
  AND C.PRODUCT_GROUP_CODE  = D.PRODUCT_GROUP_CODE
  AND D.DOSSIER_ID          = E.DOSSIER_ID(+)
  AND C.DOSSIER_ID          = E.DOSSIER_ID(+)
  AND C.PRODUCT_GROUP_CODE  = E.PRODUCT_GROUP_CODE(+)
  AND A.DOSSIER_ID          = FF.DOSSIER_ID
  --AND A.DOSSIER_CATEGORY_ID like coalesce(v('P19_CATEGORIE'),'%')
  --AND A.RESOURCE_ID         like coalesce(v('P19_PARTNER'),'%')
  --AND A.LETTER_NUMBER_YEAR  like coalesce(v('P19_YEAR'),'%')
) WHERE 1=1 
    --AND UPPER(CRS) like coalesce(v('P19_CRS'),'%')
ORDER BY DOSSIER_ID DESC,PRODUCT_CODE
;
