--------------------------------------------------------
--  DDL for View XXCT_GET_CURR_PREV_DIFF_AMOUNT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXCT"."XXCT_GET_CURR_PREV_DIFF_AMOUNT" ("DOSSIER_ID", "PREV_AMOUNT", "CURR_AMOUNT", "DIFFERENCE_AMOUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH L_PREV_AMOUNT AS (
        SELECT DOSSIER_ID,SUM(AMOUNT) PREV_AMOUNT FROM xxct_dssr_prdct_grps_hst WHERE DOSSIER_STATUS_NEW = 'AFGESLOTEN' AND (DOSSIER_ID,MANDATE_CYCLE) IN (
        SELECT DOSSIER_ID,MAX(MANDATE_CYCLE) MANDATE_CYCLE FROM (
        SELECT A.DOSSIER_ID,A.MANDATE_CYCLE FROM xxct_dssr_prdct_grps_hst A,XXCT_DOSSIERS B
        WHERE A.DOSSIER_ID = B.DOSSIER_ID AND A.MANDATE_CYCLE < B.MANDATE_CYCLE AND A.DOSSIER_STATUS_NEW = 'AFGESLOTEN' ORDER BY 1
        ) GROUP BY DOSSIER_ID
        )GROUP BY DOSSIER_ID),
    L_CURR_AMOUNT AS (
        SELECT C.DOSSIER_ID,SUM(AMOUNT) CURR_AMOUNT FROM xxct_dossier_product_groups C,XXCT_DOSSIERS D 
        WHERE C.DOSSIER_ID = D.DOSSIER_ID AND D.STATUS IN ('OPEN','CONTROLE','PROCURATIE','HEROPEND') GROUP BY C.DOSSIER_ID
        )
    SELECT B.DOSSIER_ID,PREV_AMOUNT,CURR_AMOUNT,(NVL(CURR_AMOUNT,0) - NVL(PREV_AMOUNT,0)) DIFFERENCE_AMOUNT
      FROM L_PREV_AMOUNT A,L_CURR_AMOUNT B
     WHERE A.DOSSIER_ID(+) = B.DOSSIER_ID
     ORDER BY 1 DESC
;
