--------------------------------------------------------
--  DDL for View XXCT_ALL_APPROVAL_LEVEL_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXCT"."XXCT_ALL_APPROVAL_LEVEL_V" ("SWIMLANE", "BONUSPARTNERTYPE", "DOSSIERTYPE", "ACTIONTYPE", "APPROVALLEVEL", "MINAMOUNT", "MAXAMOUNT", "ROLEAPPROVALLEVELFROM", "ROLEAPPROVALLEVELTO", "DESCRIPTION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT SWIMLANE,(SELECT CODE FROM xxct_lookup_values WHERE lookup_type ='BONUSPARTNER_TYPES' and id = BONUSPARTNERTYPE_ID) BONUSPARTNERTYPE,
(SELECT CODE FROM xxct_lookup_values WHERE lookup_type ='DOSSIER_TYPES' and id = DOSSIERTYPE_ID) DOSSIERTYPE,
(SELECT CODE FROM xxct_lookup_values WHERE lookup_type ='ACTION_TYPES' and id = ACTIONTYPE_ID) ACTIONTYPE,
APPROVALLEVEL,MINAMOUNT, MAXAMOUNT,
(SELECT role_key FROM xxct_roles WHERE ID = ROLEAPPROVALLEVELFROM ) ROLEAPPROVALLEVELFROM,
(SELECT role_key FROM xxct_roles WHERE ID = ROLEAPPROVALLEVELTO ) ROLEAPPROVALLEVELTO, DESCRIPTION
FROM XXCT_SPCTWFLEVELS
;
