--------------------------------------------------------
--  DDL for View XXCT_DOSSIERS_OVERVIEW_PAGE20_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXCT"."XXCT_DOSSIERS_OVERVIEW_PAGE20_V" ("DOSSIER_ID", "LETTER_NUMBER", "V_CODE_BUSINESS_PARTNER", "BUSINESS_PARTNER", "CREATION_DATE", "START_DATE", "PAYMENT_TYPE_MEANING", "CATEGORY", "AMOUNT", "DOSSIER_TYPE", "DOSSIER_TYPE_MEANING", "STATUS", "STATUS_MEANING", "ACTION_BY", "WASTE_BASKET", "INVOICE_NUMBER", "LETTER_NUMBER_YEAR", "LETTER_NUMBER_SEQUENCE", "LETTER_NUMBER_PERIOD", "LETTER_SUFFIX", "ACTION_START_DATE", "ACTION_END_DATE", "DOSSIER_CATEGORY_ID", "PARENT_DOSSIER_ID", "MANDATE_CYCLE", "FINANCIAL_CLOSE", "FITAR_FILE_NAME", "FITAR_EXTRACT_DATE", "EXPORT_AGAIN", "STATUS_DATE", "HOLD_PAYMENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT A.DOSSIER_ID,LETTER_NUMBER, V_CODE_BUSINESS_PARTNER, BUSINESS_PARTNER,CREATION_DATE,START_DATE,PAYMENT_TYPE_MEANING,CATEGORY,AMOUNT,DOSSIER_TYPE,DOSSIER_TYPE_MEANING,STATUS,STATUS_MEANING,
       CASE WHEN STATUS = 'FACTURATIE' THEN 'Financedesk' WHEN STATUS = 'AFGESLOTEN' THEN 'Geen'  WHEN STATUS IN ('OPEN','HEROPEND') THEN 'Retail Support'
            WHEN STATUS = 'CONTROLE' THEN
                CASE WHEN DIFFERENCE_AMOUNT < 0 THEN--CHANGE_TYPE = 'DECREASE' THEN
                    (SELECT BB.DISPLAY_NAME FROM XXCT_LOOKUP_VALUES AA,XXCT_USERS BB WHERE AA.LOOKUP_TYPE = 'VRIJVAL_CONTROLEUR' AND UPPER(BB.RUIS_NAME) = UPPER(AA.CODE) AND TO_DATE(SYSDATE,'DD-MM-YYYY') BETWEEN 
                                   TO_DATE(START_DATE_ACTIVE,'DD-MM-YYYY') AND NVL(TO_DATE(END_DATE_ACTIVE,'DD-MM-YYYY'), TO_DATE(SYSDATE,'DD-MM-YYYY'))
                                AND ENABLED_FLAG = 'Y')
                ELSE
                (SELECT (SELECT DISPLAY_NAME FROM XXCT_USERS WHERE RUIS_NAME = CHANNEL_MANAGER_OTHER)
                    FROM WKSP_XXPM.XXPM_PARTNERS_EXTRA_V WHERE PARTNER_VCODE = V_CODE_BUSINESS_PARTNER) END
            WHEN STATUS = 'PROCURATIE' THEN 
                CASE WHEN A.CHANGE_TYPE = 'INCREASE' THEN 
                (SELECT LISTAGG((get_approval_on_date ( roleid , sysdate )),', ') WITHIN GROUP (ORDER BY roleid) action_by FROM (
                   ( SELECT 'CT APPROVER '||A.PARTNER_FLOW_TYPE||' L'|| LEVEL ROLEID FROM DUAL CONNECT BY LEVEL <=(
                    SELECT MAX(SUBSTR(ROLEAPPROVALLEVELTO,-1)) 
                    FROM XXCT_ALL_APPROVAL_LEVEL_V WHERE BONUSPARTNERTYPE = A.PARTNER_FLOW_TYPE AND DOSSIERTYPE = DECODE(A.DOSSIER_TYPE,'PAYMENT','RESERVATION',DOSSIER_TYPE)
                        AND ACTIONTYPE = DECODE(A.DOSSIER_TYPE,'PAYMENT','PAYMENT','CREADITING','PAYMENT',NVL(CHANGE_TYPE,ACTION_TYPE)) AND AA.DIFFERENCE_AMOUNT BETWEEN MINAMOUNT AND MAXAMOUNT
                        )
        )
        MINUS
            (SELECT DECODE(ACTION,'Approve','CT APPROVER '||A.PARTNER_FLOW_TYPE||' L1','Reject') aa
               FROM xxct_wf_history_tmp_v WHERE INITIATOR LIKE A.DOSSIER_ID||'-'||A.MANDATE_CYCLE and action in ('Approve','Reject') and nodename like '%L1')
            UNION
             (SELECT DECODE(ACTION,'Approve','CT APPROVER '||A.PARTNER_FLOW_TYPE||' L2','Reject') aa
               FROM xxct_wf_history_tmp_v WHERE INITIATOR LIKE A.DOSSIER_ID||'-'||A.MANDATE_CYCLE and action in ('Approve','Reject') and nodename like '%L2')
        ))
                ELSE
                (SELECT LISTAGG((get_approval_on_date ( roleid , sysdate )),', ') WITHIN GROUP (ORDER BY roleid) action_by FROM (
                   ( SELECT 'CT APPROVER '||A.PARTNER_FLOW_TYPE||' L'|| LEVEL ROLEID FROM DUAL CONNECT BY LEVEL <=(
                    SELECT MAX(SUBSTR(ROLEAPPROVALLEVELTO,-1)) 
                    FROM XXCT_ALL_APPROVAL_LEVEL_V WHERE BONUSPARTNERTYPE = A.PARTNER_FLOW_TYPE AND DOSSIERTYPE = DECODE(A.DOSSIER_TYPE,'PAYMENT','RESERVATION',DOSSIER_TYPE)
                        AND ACTIONTYPE = DECODE(A.DOSSIER_TYPE,'PAYMENT','PAYMENT','CREADITING','PAYMENT',NVL(CHANGE_TYPE,ACTION_TYPE)) AND AMOUNT BETWEEN MINAMOUNT AND MAXAMOUNT
                        )
        )
        MINUS
            (SELECT DECODE(ACTION,'Approve','CT APPROVER '||A.PARTNER_FLOW_TYPE||' L1','Reject') aa
               FROM xxct_wf_history_tmp_v WHERE INITIATOR LIKE A.DOSSIER_ID||'-'||A.MANDATE_CYCLE and action in ('Approve','Reject') and nodename like '%L1')
            UNION
             (SELECT DECODE(ACTION,'Approve','CT APPROVER '||A.PARTNER_FLOW_TYPE||' L2','Reject') aa
               FROM xxct_wf_history_tmp_v WHERE INITIATOR LIKE A.DOSSIER_ID||'-'||A.MANDATE_CYCLE and action in ('Approve','Reject') and nodename like '%L2')
        )) END
            END ACTION_BY,
            WASTE_BASKET,
            INVOICE_NUMBER,LETTER_NUMBER_YEAR,LETTER_NUMBER_SEQUENCE, LETTER_NUMBER_PERIOD, LETTER_SUFFIX,
            ACTION_START_DATE, ACTION_END_DATE, DOSSIER_CATEGORY_ID, PARENT_DOSSIER_ID, MANDATE_CYCLE, FINANCIAL_CLOSE, 
            FITAR_FILE_NAME, FITAR_EXTRACT_DATE, EXPORT_AGAIN, STATUS_DATE,DECODE(A.HOLD_PAYMENT, 'Y', 'Ja', 'Nee') HOLD_PAYMENT
FROM XXCT_DOSSIERS_V A,XXCT_GET_CURR_PREV_DIFF_AMOUNT AA
WHERE 1=1 
AND A.DOSSIER_ID                  = AA.DOSSIER_ID(+)
--AND instr(nvl(v('P20_TYPE_FILTER'), '!'),dossier_type) > 0
AND (A.DOSSIER_TYPE = V('P20_RESERVATION') OR A.DOSSIER_TYPE = V('P20_CREDITING') OR A.DOSSIER_TYPE = V('P20_PAYMENT'))
AND V('P20_OWNED_BY_ME') IS NULL
AND A.dossier_category_id         LIKE nvl(V('P20_CATEGORY'),'%')
AND nvl(A.resource_id, - 9999)    = nvl(V('P20_RESOURCE'),nvl(resource_id, - 9999))
AND A.letter_number_year          LIKE nvl(V('P20_YEAR'),'%')
AND A.MAIN_CATEGORY_CODE          LIKE NVL(V('P20_CRS'),'%')
AND A.action_start_date           >= nvl(TO_DATE(V('P20_START_DATE'), 'DD-MM-YYYY'), sysdate - 1000000)
AND A.action_end_date             <= nvl(TO_DATE(V('P20_END_DATE'),'DD-MM-YYYY'), sysdate + 1000000)
AND nvl(A.amount, 0)              BETWEEN nvl(TO_NUMBER(replace(V('P20_AMOUNT_FROM'),'.','')), - 99999999999)
                                    AND nvl(TO_NUMBER(replace(V('P20_AMOUNT_TO'),'.','')),99999999999)
ORDER BY 1 DESC
;
