--------------------------------------------------------
--  DDL for Index XXAPI_BRO_IDX2
--------------------------------------------------------

  CREATE INDEX "WKSP_XXAPI"."XXAPI_BRO_IDX2" ON "WKSP_XXAPI"."XXAPI_BATCH_RUN_INFO" ("BRO_BRN_ID", "BRO_NUMBER") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
