--------------------------------------------------------
--  DDL for Index XXAPI_BCS_IDX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "WKSP_XXAPI"."XXAPI_BCS_IDX1" ON "WKSP_XXAPI"."XXAPI_BATCH_COUNTERS" ("BCS_BAH_CODE", "BCS_CODE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
