--------------------------------------------------------
--  DDL for Index XXAPI_API_USERS_APPLICATION_CODE_NAME_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "WKSP_XXAPI"."XXAPI_API_USERS_APPLICATION_CODE_NAME_UNQ" ON "WKSP_XXAPI"."XXAPI_API_USERS" ("APPLICATION_CODE_NAME", "SCOPE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
