--------------------------------------------------------
--  DDL for Index XXAPI_BRN_IDX4
--------------------------------------------------------

  CREATE UNIQUE INDEX "WKSP_XXAPI"."XXAPI_BRN_IDX4" ON "WKSP_XXAPI"."XXAPI_BATCH_RUNS" ("BRN_BAH_CODE", "BRN_STARTDATE") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
