--------------------------------------------------------
--  DDL for View XXPM_PARTNERS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_XXPM"."XXPM_PARTNERS_V" ("MAIN_PARTNER", "PARTNER_ID", "PARTNER_NAME", "PARTNER_VCODE", "PARTNER_NUMBER", "ORACLE_CUSTOMER_NR", "KVK_NUMBER", "VAT_CODE", "PARTNER_TYPE", "EMAIL_ADDRESS", "EMAIL_ADDRESS_INVOICE", "PHONE_NUMBER", "IBAN_NUMBER", "VAMO_TYPE_CODE", "CHAIN_ID", "MAIN_PARTNER_ID", "START_DATE", "END_DATE", "CHANNEL_MANAGER", "RETAIL_SUPPORT_MANAGER", "IVR_CODE", "PARTNER_CHANNEL", "IP_WHITELIST", "TELFORT_CODE", "TABO_CODE", "CERTIFICATE_DATE", "PARTNER_URL", "INDICATOR_ATTRIBUTE_1", "INDICATOR_ATTRIBUTE_2", "INDICATOR_ATTRIBUTE_3", "INDICATOR_ATTRIBUTE_4", "INDICATOR_ATTRIBUTE_5", "INDICATOR_ATTRIBUTE_6", "INDICATOR_ATTRIBUTE_7", "INDICATOR_ATTRIBUTE_8", "INDICATOR_ATTRIBUTE_9", "INDICATOR_ATTRIBUTE_10", "FLEX_ATTRIBUTE_1", "FLEX_ATTRIBUTE_2", "FLEX_ATTRIBUTE_3", "FLEX_ATTRIBUTE_4", "FLEX_ATTRIBUTE_5", "FLEX_ATTRIBUTE_6", "FLEX_ATTRIBUTE_7", "FLEX_ATTRIBUTE_8", "FLEX_ATTRIBUTE_9", "FLEX_ATTRIBUTE_10", "CREATION_DATE", "CREATED_BY", "LAST_UPDATE_DATE", "LAST_UPDATED_BY", "ADDRESS_RESIDENCE", "ADDRESS_STREET", "ADDRESS_HOUSE_NUMBER", "ADDRESS_HOUSE_NUMBER_SUFFIX", "ADDRESS_ZIP_CODE", "HOOFD_PARTNER_NAAM", "HOOFD_PARTNER_VCODE", "MARKT", "PARTNER_CLASSIFICATION_CODE", "INDICATOR_IN_EX_CODE", "SUB_PARTNER_COUNT", "SALES_CHANNEL", "SUB_SALES_CHANNEL", "BUSINESS_PARTNER_MANAGER", "BUSINESS_PARTNER_SALES_MANAGER", "CHAIN_NAME", "CENTER_CODE", "INDICATOR_IN_EX", "PARTNER_CLASSIFICATION", "VAMO_TYPE", "NAME_ON_INVOICE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT bas."MAIN_PARTNER", 
          bas."PARTNER_ID", 
          bas."PARTNER_NAME", 
          bas."PARTNER_VCODE", 
          bas."PARTNER_NUMBER", 
          bas."ORACLE_CUSTOMER_NR", 
          bas."KVK_NUMBER", 
          bas."VAT_CODE", 
          bas."PARTNER_TYPE", 
          bas."EMAIL_ADDRESS", 
          bas."EMAIL_ADDRESS_INVOICE", 
          bas."PHONE_NUMBER", 
          bas."IBAN_NUMBER", 
          bas."VAMO_TYPE_CODE", 
          bas."CHAIN_ID", 
          bas."MAIN_PARTNER_ID", 
          bas."START_DATE", 
          bas."END_DATE", 
          bas."CHANNEL_MANAGER", 
          bas."RETAIL_SUPPORT_MANAGER", 
          bas."IVR_CODE", 
          bas."PARTNER_CHANNEL", 
          bas."IP_WHITELIST", 
          bas."TELFORT_CODE", 
          bas."TABO_CODE", 
          bas."CERTIFICATE_DATE", 
          bas."PARTNER_URL", 
          bas."INDICATOR_ATTRIBUTE_1", 
          bas."INDICATOR_ATTRIBUTE_2", 
          bas."INDICATOR_ATTRIBUTE_3", 
          bas."INDICATOR_ATTRIBUTE_4", 
          bas."INDICATOR_ATTRIBUTE_5", 
          bas."INDICATOR_ATTRIBUTE_6", 
          bas."INDICATOR_ATTRIBUTE_7", 
          bas."INDICATOR_ATTRIBUTE_8", 
          bas."INDICATOR_ATTRIBUTE_9", 
          bas."INDICATOR_ATTRIBUTE_10", 
          bas."FLEX_ATTRIBUTE_1", 
          bas."FLEX_ATTRIBUTE_2", 
          bas."FLEX_ATTRIBUTE_3", 
          bas."FLEX_ATTRIBUTE_4", 
          bas."FLEX_ATTRIBUTE_5", 
          bas."FLEX_ATTRIBUTE_6", 
          bas."FLEX_ATTRIBUTE_7", 
          bas."FLEX_ATTRIBUTE_8", 
          bas."FLEX_ATTRIBUTE_9", 
          bas."FLEX_ATTRIBUTE_10", 
          bas."CREATION_DATE", 
          bas."CREATED_BY", 
          bas."LAST_UPDATE_DATE", 
          bas."LAST_UPDATED_BY", 
          bas."ADDRESS_RESIDENCE", 
          bas."ADDRESS_STREET", 
          bas."ADDRESS_HOUSE_NUMBER", 
          bas."ADDRESS_HOUSE_NUMBER_SUFFIX", 
          bas."ADDRESS_ZIP_CODE", 
          bas."HOOFD_PARTNER_NAAM", 
          bas."HOOFD_PARTNER_VCODE", 
          bas."MARKT", 
          bas."PARTNER_CLASSIFICATION_CODE", 
          bas."INDICATOR_IN_EX_CODE", 
          bas."SUB_PARTNER_COUNT", 
          bas."SALES_CHANNEL", 
          bas."SUB_SALES_CHANNEL", 
          bas."BUSINESS_PARTNER_MANAGER", 
          bas."BUSINESS_PARTNER_SALES_MANAGER", 
          c.chain_name, 
          c.center_code, 
          t1.meaning indicator_in_ex, 
          t2.meaning partner_classification, 
          t.meaning vamo_type ,
          bas.name_on_invoice
     FROM (SELECT 'Ja' main_partner, 
                  p.partner_id, 
                  p.partner_name, 
                  p.partner_vcode, 
                  p.partner_number, 
                  p.oracle_customer_nr, 
                  p.kvk_number, 
                  p.vat_code, 
                  DECODE (p.partner_type,'M', 'Hoofd-Partner','S', 'Sub-Partner',p.partner_type) partner_type, 
                  p.email_address, 
                  p.email_address_invoice, 
                  p.phone_number, 
                  p.iban_number, 
                  p.vamo_type vamo_type_code, 
                  p.chain_id, 
                  p.main_partner_id,--      DECODE(p.partner_status,'D','Dealer','SD','Sub-Dealer','E','Exit',p.partner_status) partner_status 
                  p.start_date, 
                  nvl(p.end_date,to_date('31-12-9998','DD-MM-YYYY')) end_date,                           --,      p.partner_exit 
                  (SELECT DISTINCT pap.full_name FROM XXPM_ALL_PEOPLE pap WHERE pap.national_identifier = p.channel_manager) channel_manager, 
                  p.retail_support_manager, 
                  p.ivr_code, 
                  p.partner_channel, 
                  p.ip_whitelist, 
                  p.telfort_code, 
                  p.tabo_code, 
                  p.certificate_date, 
                  p.partner_url, 
                  p.indicator_attribute_1, 
                  p.indicator_attribute_2, 
                  p.indicator_attribute_3, 
                  p.indicator_attribute_4, 
                  p.indicator_attribute_5, 
                  p.indicator_attribute_6, 
                  p.indicator_attribute_7, 
                  p.indicator_attribute_8, 
                  p.indicator_attribute_9, 
                  p.indicator_attribute_10, 
                  p.flex_attribute_1, 
                  p.flex_attribute_2, 
                  p.flex_attribute_3, 
                  p.flex_attribute_4, 
                  p.flex_attribute_5, 
                  p.flex_attribute_6, 
                  p.flex_attribute_7, 
                  p.flex_attribute_8, 
                  p.flex_attribute_9, 
                  p.flex_attribute_10, 
                  p.creation_date, 
                  p.created_by, 
                  p.last_update_date, 
                  p.last_updated_by, 
                  a.address_residence, 
                  a.address_street, 
                  a.address_house_number, 
                  a.address_house_number_suffix, 
                  a.address_zip_code, 
                  NULL hoofd_partner_naam, 
                  p.partner_vcode hoofd_partner_vcode, 
                  DECODE (p.partner_channel, 'BM', 'Business', 'Consumenten') markt, 
                  p.partner_classification partner_classification_code, 
                  p.indicator_in_ex indicator_in_ex_code, 
                  NVL (sub_partner_count, 0) sub_partner_count, 
                  c.sales_channel, 
                  c.sub_sales_channel, 
                  p.BUSINESS_PARTNER_MANAGER, 
                  p.BUSINESS_PARTNER_SALES_MANAGER, 
                  p.name_on_invoice
             FROM xxpm_partners p, 
                  (SELECT * FROM xxpm_addresses a1 WHERE address_id = (SELECT MIN (a2.address_id) FROM xxpm_addresses a2 WHERE a2.partner_id = a1.partner_id)) a, 
                  (SELECT main_partner_id, COUNT (*) sub_partner_count FROM xxpm_partners WHERE main_partner_id IS NOT NULL AND main_partner_id <> partner_id 
                    GROUP BY main_partner_id) b, 
                  xxpm_chains c 
            WHERE 1 = 1 
              AND p.partner_type = 'M' 
              AND a.partner_id(+) = p.partner_id 
              AND p.partner_id = NVL (p.main_partner_id, p.partner_id) 
              AND b.main_partner_id(+) = p.partner_id 
              AND c.chain_id(+) = p.chain_id 
              AND p.partner_classification <> -1
              AND P.PARTNER_CLASSIFICATION <> 10 ---------Added & Commented By TechM Team for MWT-587/588
        ---------- Below Union Added By TechM Team for MWT-587/588
UNION
        SELECT 'Ja' main_partner,
               p.partner_id,
               p.partner_name,
               p.partner_vcode,
               p.partner_number,
               p.oracle_customer_nr,
               p.kvk_number,
               p.vat_code,
               DECODE(p.partner_type,'M','Hoofd-Partner','S','Sub-Partner',p.partner_type) partner_type,
               p.email_address,
               p.email_address_invoice,
               p.phone_number,
               p.iban_number,
               p.vamo_type vamo_type_code,
               p.chain_id,
               p.main_partner_id, --,      DECODE(p.partner_status,'D','Dealer','SD','Sub-Dealer','E','Exit',p.partner_status) partner_status 
               p.start_date,
               nvl(p.end_date,to_date('31-12-9998','DD-MM-YYYY')) end_date,                           --,      p.partner_exit 
               (SELECT DISTINCT pap.full_name FROM XXPM_ALL_PEOPLE pap WHERE pap.national_identifier = p.channel_manager) channel_manager, 
               p.retail_support_manager,
               p.ivr_code,
               p.partner_channel,
               p.ip_whitelist,
               p.telfort_code,
               p.tabo_code,
               p.certificate_date,
               p.partner_url, 
               p.indicator_attribute_1, 
               p.indicator_attribute_2, 
               p.indicator_attribute_3, 
               p.indicator_attribute_4, 
               p.indicator_attribute_5, 
               p.indicator_attribute_6, 
               p.indicator_attribute_7, 
               p.indicator_attribute_8, 
               p.indicator_attribute_9, 
               p.indicator_attribute_10, 
               p.flex_attribute_1, 
               p.flex_attribute_2, 
               p.flex_attribute_3, 
               p.flex_attribute_4, 
               p.flex_attribute_5, 
               p.flex_attribute_6, 
               p.flex_attribute_7, 
               p.flex_attribute_8, 
               p.flex_attribute_9, 
               p.flex_attribute_10, 
               p.creation_date, 
               p.created_by, 
               p.last_update_date, 
               p.last_updated_by, 
               a.address_residence, 
               a.address_street, 
               a.address_house_number, 
               a.address_house_number_suffix, 
               a.address_zip_code, 
               NULL hoofd_partner_naam, 
               p.partner_vcode hoofd_partner_vcode, 
               DECODE (p.partner_channel, 'BM', 'Business', 'Consumenten') markt, 
               p.partner_classification partner_classification_code, 
               p.indicator_in_ex indicator_in_ex_code, 
               NVL (sub_partner_count, 0) sub_partner_count, 
               c.sales_channel, 
               c.sub_sales_channel, 
               p.BUSINESS_PARTNER_MANAGER, 
               p.BUSINESS_PARTNER_SALES_MANAGER, 
               p.name_on_invoice
          FROM xxpm_partners p, 
               (SELECT * FROM xxpm_addresses a1 WHERE address_id = (SELECT MIN (a2.address_id) FROM xxpm_addresses a2 WHERE a2.partner_id = a1.partner_id)) a, 
               (SELECT main_partner_id, COUNT (*) sub_partner_count FROM xxpm_partners WHERE main_partner_id IS NOT NULL 
                            AND main_partner_id <> partner_id GROUP BY main_partner_id) b, 
                xxpm_chains c 
        WHERE 1 = 1 
          AND p.partner_type IN ('M','S')
          AND a.partner_id(+) = p.partner_id 
          AND p.partner_id = NVL (p.main_partner_id, p.partner_id) 
          AND b.main_partner_id(+) = p.partner_id 
          AND c.chain_id(+) = p.chain_id 
          AND p.partner_classification <> -1 
          AND V('G_ROLE_NAME') = 'PM BPO Partners'
          AND P.PARTNER_CLASSIFICATION = 10
-------------End MWT-587/588-----------
UNION 
        SELECT 'Nee' main_partner, 
               p.partner_id, 
               p.partner_name, 
               p.partner_vcode, 
               p.partner_number, 
               p.oracle_customer_nr, 
               p.kvk_number, 
               p.vat_code, 
               DECODE (p.partner_type, 'M', 'Hoofd-Partner', 'S', 'Sub-Partner', p.partner_type) partner_type, 
               p.email_address, 
               p.email_address_invoice, 
               p.phone_number, 
               p.iban_number, 
               p.vamo_type vamo_type_code, 
               c.chain_id, 
               p.main_partner_id, --,      DECODE(p.partner_status,'D','Dealer','SD','Sub-Dealer','E','Exit',p.partner_status) partner_status 
               p.start_date, 
               nvl(p.end_date,to_date('31-12-9998','DD-MM-YYYY')) end_date,                  --      p.partner_exit 
               (SELECT DISTINCT pap.full_name FROM XXPM_ALL_PEOPLE pap WHERE pap.national_identifier = m.channel_manager) channel_manager, 
               m.retail_support_manager, 
               p.ivr_code, 
               p.partner_channel, 
               p.ip_whitelist, 
               p.telfort_code, 
               p.tabo_code, 
               p.certificate_date, 
               p.partner_url, 
               p.indicator_attribute_1, 
               p.indicator_attribute_2, 
               p.indicator_attribute_3, 
               p.indicator_attribute_4, 
               p.indicator_attribute_5, 
               p.indicator_attribute_6, 
               p.indicator_attribute_7, 
               p.indicator_attribute_8, 
               p.indicator_attribute_9, 
               p.indicator_attribute_10, 
               p.flex_attribute_1, 
               p.flex_attribute_2, 
               p.flex_attribute_3, 
               p.flex_attribute_4, 
               p.flex_attribute_5, 
               p.flex_attribute_6, 
               p.flex_attribute_7, 
               p.flex_attribute_8, 
               p.flex_attribute_9, 
               p.flex_attribute_10, 
               p.creation_date, 
               p.created_by, 
               p.last_update_date, 
               p.last_updated_by, 
               a.address_residence, 
               a.address_street, 
               a.address_house_number, 
               a.address_house_number_suffix, 
               a.address_zip_code, 
               m.partner_name hoofd_partner_naam, 
               m.partner_vcode hoofd_partner_vcode, 
               DECODE (p.partner_channel, 'BM', 'Business', 'Consumenten') markt, 
               p.partner_classification partner_classification_code, 
               p.indicator_in_ex indicator_in_ex_code, 
               0 sub_partner_count, 
               c.sales_channel  , 
               c.sub_sales_channel, 
               m.BUSINESS_PARTNER_MANAGER, 
               m.BUSINESS_PARTNER_SALES_MANAGER,
               p.name_on_invoice
          FROM xxpm_partners p, 
               (SELECT * FROM xxpm_addresses a1 WHERE address_id = (SELECT MIN (a2.address_id) FROM xxpm_addresses a2 WHERE a2.partner_id = a1.partner_id)) a, 
                xxpm_partners m, 
                xxpm_chains c 
          WHERE 1 = 1 
            AND p.partner_type = 'S'
            AND a.partner_id(+) = p.partner_id 
            --AND p.partner_id <> NVL (p.main_partner_id, p.partner_id) -- verwijderd op 20-09-2022 
            AND m.partner_id(+) = p.main_partner_id 
            AND c.chain_id(+) = m.chain_id 
            AND p.main_partner_id <> -2 
            AND p.partner_classification <> -1
            ) bas, 
          xxpm_chains c, 
          XXPM_LOOKUP_VALUES t1, 
          XXPM_LOOKUP_VALUES t2, 
          XXPM_LOOKUP_VALUES t 
    WHERE 1 = 1 
      AND t1.lookup_type = 'INTERN_EXTERN' 
      AND t1.enabled_flag = 'Y' 
      AND t1.code = bas.indicator_in_ex_code 
          -- 
      AND t2.lookup_type LIKE 'PARTNER_CLASSIFICATION' 
      AND t2.enabled_flag = 'Y' 
      AND t2.code = bas.partner_classification_code 
          -- 
      AND t.lookup_type = 'VAMO_TYPE' 
      AND t.enabled_flag = 'Y' 
      AND t.code = bas.vamo_type_code 
          -- 
      AND c.chain_id(+) = bas.chain_id
;
